version: "3"
services:
    game-server:
        image: coderone.azurecr.io/game-server:1523 #1065
        volumes:
            - ./logs:/app/logs

    python3-agent:
        build:
            context: core
            dockerfile: Dockerfile

    python3-agent-dev:
        build:
            context: core
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app

